### ISSUE TITLE
Checklist Author/Viewer

### ISSUE THREAD

**Issue by sgoshorn** [CCALI/caw#25]
A list of tasks to do, not warranting individual issues yet.
- Create quiz
- [ ] Subject area should be picklist
- [ ] Set allowable time period to run the quiz? 
- Quiz Detail view
- [ ] Indicate the correct T/F in detail
- List of My Questions
- [ ] Sort by columns
- [ ] Question type icon
- [ ] Show how many quizzes use a question
- [ ] Show if question is shared/public
- [ ] Show creation and modified date?
- [ ] Performance on the question - how many students got it right
- [ ] Clone a question
- List of Library Questions
- [ ] Clone a question (preserving attribution)
- List of My Quizzes
- [ ] Clone a quiz
- Questions in Quiz
- [ ] Sort by columns
- [ ] Let author add/remove existing questions
- LessonPast Report
- [ ] Check: Sorting by user name also sorts the page names??
- Lesson Run Page
- [ ] Turn off 'Resume' for quizzes
