### ISSUE TITLE
Checklist for a Standalone Package

### ISSUE THREAD

**Issue by sgoshorn** [CCALI/caw#96]
What needs to be added or modified to make QW standalone and not dependent on Drupal. 
- [ ] LessonRun table
- [ ] Student user records (login for students)
- [ ] Hooks to link lesson viewer ScoreSave functionality with server records
- [ ] Place to publish quizzes
- [ ] Lesson Viewer that runs off static folder of 'published' QW quizzes
- [ ] LessonPast reports
Anything else?
